# basic options
title: My blog title
author: Bouamar ELOUAHHABI
email: iambouamar@gmail.com
description: A wonderful site
twitter_username: iambouamar
github_username:  iambouamar

# Build settings
markdown: kramdown
theme: minima
